### ISSUE TITLE
How can I get these files?

### ISSUE THREAD

**Issue by 771613990** [MRLoghmani/rcfusion#1]
Hello，I‘msorry，How can I get these files? 
’’tsne_feat_rgb.npy；tsne_feat_depth.npy；tsne_feat_rgbd.npy；feat_preds.npy

**Comment by MRLoghmani** [comment]
You don't need to load these files. The train_and_eval.py script is actually creating them during training. Anyway, these were used for debugging during the development of the method and are not a key aspect of the algorithm.
