### ISSUE TITLE
Problem with relative paths in train_eval.py and log variables in utils.py

### ISSUE THREAD

**Issue by achiatti** [MRLoghmani/rcfusion#3]
Very interesting work and thanks for providing a code base with the paper. 

When launching python code/train_and_eval.py on the recommended dataset, the attached error is raised. [I am running this code outside of docker but with all the needed requirements in place.]

![image](https://user-images.githubusercontent.com/22052065/79240182-53c05180-7e69-11ea-8285-e191ae4707d3.png)

I solved the issue by creating the features folder. Shouldn't it be specified somewhere in the readme to create an empty features folder at the right location? 

After fixing that, more issues are raised due to undefined variables in code/utils.py (e.g., log_dir). 
![image](https://user-images.githubusercontent.com/22052065/79240825-2a53f580-7e6a-11ea-857d-65b137ff1053.png)

As-is, the train_eval.py script does not complete running even for a single epoch.

**Comment by MRLoghmani** [comment]
Thank you for reporting this problem. I will look into it as soon as possible, but the current coronavirus situation will slow down my intervention. I will notify you as soon as I commit the new version.

In the spirit of helping you get the code running as quickly as possible, I would suggest you comment line 578 of code/train_and_eval.py. Not calling log_file() should solve your issue.

**Comment by MRLoghmani** [comment]
With the last commits, I removed these lines since they were mostly for debugging purposes. It should run without errors now.

Thanks again for reporting the issue!
I will close it now.
